name: KUBESEC
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas=2.0.2
  - pyyaml=6.0
  - pytest=7.3.1
  - requests=2.29.0
  - typer=0.9.0
  - jschema-to-python
  - ruamel.yaml
  - sarif-om
