'''
Akond Rahman 
April 30, 2021 
Placeholder to save test constants 
'''

_test_yaml          = 'TEST_ARTIFACTS/dataimage.airflowimage.manifests.deployment.yaml'
_secret_yaml1       = 'TEST_ARTIFACTS/helm.values.yaml'
_secret_yaml2       = 'TEST_ARTIFACTS/tango.values.yaml'
_secret_yaml3       = 'TEST_ARTIFACTS/charts.values.yaml'
_secret_yaml4       = 'TEST_ARTIFACTS/skampi.values.yaml'
_secret_yaml5       = 'TEST_ARTIFACTS/minecraft.values.yaml'
_secret_yaml6       = 'TEST_ARTIFACTS/kubecf.values.yaml'
_secret_yaml7       = 'TEST_ARTIFACTS/nextcloud.values.yaml'
_secret_yaml8       = 'TEST_ARTIFACTS/keycloak.values.yaml'
_secret_yaml9       = 'TEST_ARTIFACTS/empty.yml'
_secret_yaml10      = 'TEST_ARTIFACTS/kubecf.values.yaml'
_cert_yaml          = 'TEST_ARTIFACTS/sni.values.yaml'
_rsa_key_yaml       = 'TEST_ARTIFACTS/hello.values.yaml' 
_helm_script1       = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/stackgres/stackgres-k8s/install/helm/stackgres-operator/values.yaml'
_helm_script2       = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/skampi/charts/skampi/charts/tango-base/values.yaml'
_helm_script3       = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/skampi/charts/skampi/charts/archiver/values.yaml'
_helm_script4       = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/skampi/charts/skampi/charts/dsh-lmc-prototype/values.yaml' 
_helm_script5       = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/justin@kubernetes/src/services/minecraft/values.yaml'
_fp_script1         = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/kubecf/deploy/helm/kubecf/values.yaml'
_fp_script2         = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/justin@kubernetes/src/services/nextcloud/values.yaml'
_fp_script3         = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/justin@kubernetes/src/services/postgres/values.yaml'
_fp_script4         = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/skampi/partial-deployments/tango-db-standalone/values.yaml'
_fp_script5         = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/justin@kubernetes/src/services/postgres/values-production.yaml'
_fp_script6         = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/justin@kubernetes/src/services/keycloak/values.yaml'
_fp_script7         = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/kubecf/deploy/helm/kubecf/values.yaml'
_fp_script8         = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/k8s-ingress/examples/architectures/multi-controller/varnish-tea.yaml'
_fp_script9         = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/k8s-ingress/examples/tls/sni/values.yaml'
_fp_script10        = '/Users/arahman/K8S_REPOS/GITLAB_REPOS/k8s-ingress/examples/tls/hello/values.yaml'
_privi_scrip1       = 'TEST_ARTIFACTS/test.sample.pod.yaml'
_privi_scrip2       = 'TEST_ARTIFACTS/sample-nfs-server.yaml'
_privi_scrip3       = 'TEST_ARTIFACTS/artifact.nfs.server.yaml'
_privi_scrip4       = 'TEST_ARTIFACTS/deamonset1.yaml'
_privi_scrip5       = 'TEST_ARTIFACTS/calico.yaml'

_value_for_key      = '/usr/local/airflow/analytics'
_mount_path_kw      = 'mountPath' 
_spec_kw            = 'spec'
_valid_test_yaml    = 'TEST_ARTIFACTS/nginx.deployment.result.yaml'
_invalid_test_yaml1 = 'TEST_ARTIFACTS/bootstrap.debian.yaml'
_invalid_test_yaml2 = 'TEST_ARTIFACTS/githooks.yaml'
_invalid_test_yaml3 = 'TEST_ARTIFACTS/start_vault_temp.yaml'
_invalid_test_yaml4 = 'TEST_ARTIFACTS/list.k8s.yml'
_invalid_test_yaml5 = 'TEST_ARTIFACTS/tasks.main.yml'
_invalid_test_yaml6 = 'TEST_ARTIFACTS/cluster.svc.v.yaml'
_invalid_test_yaml7 = 'TEST_ARTIFACTS/reso.app.yml'
_invalid_test_yaml8 = 'TEST_ARTIFACTS/no.kind.yaml'
_true_kw            = 'TRUE'
_false_kw           = 'FALSE'
_key_kw             = 'key'
_delay_kw           = 'initialDelaySeconds'
_privilege_kw       = 'allowPrivilegeEscalation'
_name_kw            = 'name'
_none_kw            = 'NONE'


_common_error_string = 'SHOULD BE '