'''
Akond Rahman 
April 30, 2021 
Placeholder to save test constants 
'''

_test_yaml          = 'TEST_ARTIFACTS/dataimage.airflowimage.manifests.deployment.yaml'
_secret_yaml1       = 'TEST_ARTIFACTS/helm.values.yaml'
_secret_yaml2       = 'TEST_ARTIFACTS/tango.values.yaml'
_secret_yaml3       = 'TEST_ARTIFACTS/charts.values.yaml'
_secret_yaml4       = 'TEST_ARTIFACTS/skampi.values.yaml'
_secret_yaml5       = 'TEST_ARTIFACTS/minecraft.values.yaml'
_secret_yaml6       = 'TEST_ARTIFACTS/kubecf.values.yaml'
_secret_yaml7       = 'TEST_ARTIFACTS/nextcloud.values.yaml'
_secret_yaml8       = 'TEST_ARTIFACTS/keycloak.values.yaml'
_secret_yaml9       = 'TEST_ARTIFACTS/empty.yml'
_secret_yaml10      = 'TEST_ARTIFACTS/kubecf.values.yaml'
_value_for_key      = '/usr/local/airflow/analytics'
_mount_path_kw      = 'mountPath' 
_spec_kw            = 'spec'
_valid_test_yaml    = 'TEST_ARTIFACTS/nginx.deployment.result.yaml'
_invalid_test_yaml1 = 'TEST_ARTIFACTS/bootstrap.debian.yaml'
_invalid_test_yaml2 = 'TEST_ARTIFACTS/githooks.yaml'
_invalid_test_yaml3 = 'TEST_ARTIFACTS/start_vault_temp.yaml'
_invalid_test_yaml4 = 'TEST_ARTIFACTS/list.k8s.yml'
_invalid_test_yaml5 = 'TEST_ARTIFACTS/tasks.main.yml'
_invalid_test_yaml6 = 'TEST_ARTIFACTS/cluster.svc.v.yaml'
_invalid_test_yaml7 = 'TEST_ARTIFACTS/reso.app.yml'
_invalid_test_yaml8 = 'TEST_ARTIFACTS/no.kind.yaml'
_true_kw            = 'TRUE'
_false_kw           = 'FALSE'
_key_kw             = 'key'
_delay_kw           = 'initialDelaySeconds'
_privilege_kw       = 'allowPrivilegeEscalation'
_name_kw            = 'name'


_common_error_string = 'SHOULD BE '